# generated by datamodel-codegen:
#   filename:  v3.yaml
#   timestamp: 2023-01-20T10:29:57+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field

class UserId(BaseModel):
    user_id: str = Field(
        ..., description='What is used to identify a user, the format is the following: firstname@lastname' # It will probably be first@last#XXX where XXX is an identification code for duplicate names.
    )


class PasswordHash(BaseModel):
    __root__: bytes = Field(
        ..., description='A SHA-256 hash of a password (hash of a string)'
    )


class EncryptedData(BaseModel):
    __root__: bytes = Field(
        ..., description='Encrypted data, often encrypted with the password, but not always'
    )


class PublicKey(BaseModel):
    __root__: bytes = Field(
        ...,
        description="A user's public key, the key that is used to encrypt messages and send them to the user.",
    )

class PrivateKey(BaseModel):
    __root__: EncryptedData = Field(
        ...,
        description="A user's private key. It used to decrypt some important data. It is itself encrypted using the user password."
    )


class Keypair(BaseModel):
    public_key: PublicKey = ...
    private_key: PrivateKey = ...


class Language(Enum):
    fr = 'fr'
    en = 'en'
    es = 'es'
    de = 'de'
    it = 'it'

class User(BaseModel):
    user_id: UserId = ...
    firstname: Optional[str] = None
    lastname: Optional[str] = None


class ConversationId(BaseModel):
    __root__: str = Field(..., description='The identifier of a conversation.')


class ConversationInfo(BaseModel):
    conversation_id: ConversationId = ...
    key: EncryptedData = ...
    members: List[User] = Field(..., unique_items=True)
    created_at: float = ...


class ConversationsList(BaseModel):
    length: int = Field(...)
    conversations: List[ConversationInfo] = Field(..., unique_items=True)

class MessageId(BaseModel):
    __root__: str = Field(...)

class MessageBundle(BaseModel):
    message_id: MessageId = ...
    conversation_id: ConversationId = ...
    content: EncryptedData = ...
    sent_at: float = ...
    sender_id: User = ...

"""

class LanguagesInfo(BaseModel):
    mastered: Optional[List[Language]] = Field(None, unique_items=True)
    learning: Optional[List[Language]] = Field(None, unique_items=True)
    interested: Optional[List[Language]] = Field(None, unique_items=True)

class MatchingPreferences(BaseModel):
    main_interest: Optional[str] = None
    interests: Optional[List[str]] = Field(None, max_items=4, unique_items=True)
    languages: Optional[LanguagesInfo] = None
    description: Optional[str] = None

"""

# ------------------------------- Websockets interaction models ----------------------------

class SubscribeRequestDataModel(BaseModel):

    userid: str
    password_hash: str
    conversation_id: int

class WebsocketRequestModel(BaseModel):
    type: str
    data: Any

class SubscribeRequestModel(BaseModel):

    type: str
    data: SubscribeRequestDataModel